"""initial migration

Revision ID: 041f9668c18e
Revises: 
Create Date: 2025-05-15 11:28:01.784498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041f9668c18e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('nomor_hp', sa.String(length=15), nullable=False),
    sa.Column('asal_sekolah', sa.String(length=150), nullable=False),
    sa.Column('nilai_un', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tanggal_daftar', sa.DateTime(), nullable=True),
    sa.Column('diproses_oleh', sa.Integer(), nullable=True),
    sa.Column('tanggal_diproses', sa.DateTime(), nullable=True),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['diproses_oleh'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendaftaran')
    op.drop_table('user')
    # ### end Alembic commands ###
