"""Initial migration

Revision ID: 8874c5da22a9
Revises: 
Create Date: 2025-05-08 12:31:48.034168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8874c5da22a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('nomor_hp', sa.String(length=15), nullable=False),
    sa.Column('asal_sekolah', sa.String(length=150), nullable=False),
    sa.Column('nilai_un', sa.Float(), nullable=False),
    sa.Column('tanggal_daftar', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendaftaran')
    # ### end Alembic commands ###
