"""initial schema

Revision ID: d6c6cc80142f
Revises: 
Create Date: 2025-05-21 13:40:01.191678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c6cc80142f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('nomor_hp', sa.String(length=15), nullable=False),
    sa.Column('asal_sekolah', sa.String(length=150), nullable=False),
    sa.Column('nilai_un', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tanggal_daftar', sa.DateTime(), nullable=True),
    sa.Column('bukti_pembayaran', sa.String(length=255), nullable=True),
    sa.Column('tanggal_upload_pembayaran', sa.DateTime(), nullable=True),
    sa.Column('status_pembayaran', sa.String(length=20), nullable=True),
    sa.Column('konfirmasi_admin', sa.Boolean(), nullable=True),
    sa.Column('pas_foto', sa.String(length=255), nullable=True),
    sa.Column('ijazah', sa.String(length=255), nullable=True),
    sa.Column('tanggal_upload_dokumen', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diproses_oleh', sa.Integer(), nullable=True),
    sa.Column('tanggal_diproses', sa.DateTime(), nullable=True),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['diproses_oleh'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendaftaran')
    op.drop_table('user')
    # ### end Alembic commands ###
